### ISSUE TITLE
固件无法识别NVMe固态硬盘

### ISSUE THREAD

**Issue by Ma-Junhan** [DHDAXCW/NanoPi-R5S#11]
安装WD的1TB SN570后，要么无法正常启动（LAN灯插线时不亮），要么启动后在/dev目录下找不到nvme设备。作为对比，官方的FriendlyWrt固件可以正常识别到NVMe固态硬盘。

**Comment by DHDAXCW** [comment]
我没nvme固态，没法测试

**Comment by DHDAXCW** [comment]
已修复了

**Comment by ZhuangJiayu** [comment]
我用的最新固件，插nvme依旧不行，中间的lan口不识别，/dev下能看到nvme设备。官方固件正常

**Comment by ijunchang** [comment]
同样，我用了最新的固件也不能识别，不装m2可以正常使用

**Comment by DHDAXCW** [comment]
已修复，等下个版本
![image](https://user-images.githubusercontent.com/74764072/193965096-90ce175d-1348-4566-8111-11409917d0b1.png)
