### ISSUE TITLE
求个线刷emmc的固件

### ISSUE THREAD

**Issue by labubu-bear** [DHDAXCW/NanoPi-R5S#12]
如题，求大佬个r5s的线刷emmc的固件

**Comment by opoet** [comment]
现在发的两个都能先刷 emmc ，详情在第一次发布的说明里面

**Comment by labubu-bear** [comment]
> 

我看到那个说明了，也尝试线刷了，但是就是启动不起来，换了别的固件，倒是可以刷进去，但是一直以来都是用的大佬的固件，觉得优化的特别好
