### ISSUE TITLE
没有SD卡的刷机版本吗

### ISSUE THREAD

**Issue by ijunchang** [DHDAXCW/NanoPi-R5S#5]
没有SD卡的刷机版本吗

**Comment by DHDAXCW** [comment]
有啊，你直接下好固件写卡，和r4s一样卡刷，然后终端命令 dd if=/dev/zero of=/dev/mmcblk0 bs=8M count=1 然后reboot，10秒后，拔电，插sd卡上电，就从sd卡启动了。

**Comment by DHDAXCW** [comment]
要保证emmc没有系统，就会自己从sd启动了
