### ISSUE TITLE
R5S 刷新固件    插m2 WD blue SN570 500G 固态 无法启动

### ISSUE THREAD

**Issue by ijunchang** [DHDAXCW/NanoPi-R5S#6]
1. 刷入固件，默认插有m2固态，然后无法启动，软路由发烫，wan正常亮绿灯，lan灯不亮，确认网线都有插好
2. 取下m2固态，把掉电源重启，可以正常启动系统
3. 重新把m2插入正在启动的系统，无法识别，然后此时重启系统，无法启动成功
4. 固态是好的，我的用的固态是：WD blue SN570 500G

不知道有人插入m2固态能正常使用不，麻烦大佬看一下，谢谢谢谢

**Comment by DHDAXCW** [comment]
没固态，测试不了
