### ISSUE TITLE
请问这版R5S有人用了吗？WAN/LAN口是否正常？

### ISSUE THREAD

**Issue by JW1223831** [DHDAXCW/NanoPi-R5S#8]
请问这版R5S有人用了吗？WAN/LAN口是否正常？

**Comment by ijunchang** [comment]
正常使用，不要插m2固态刷机试试

**Comment by JW1223831** [comment]
> 正常使用，不要插m2固态刷机试试

好的，我刷个机试下，我不用固态，也不用HDMI，路由/插件稳定就行啦
